# Generated by Django 3.2.11 on 2022-01-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('class_name', models.CharField(blank=True, max_length=10)),
                ('roll_number', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
