# Generated by Django 3.2.11 on 2022-01-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
    ]
