# Generated by Django 3.2.11 on 2022-01-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendance_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
