# Generated by Django 3.2.11 on 2022-01-12 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0014_alter_attendance_date_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='teacher_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
