# Generated by Django 3.2.11 on 2022-01-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_remove_attendance_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
    ]
