# Generated by Django 3.2.11 on 2022-01-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20220112_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
