# Generated by Django 3.2.11 on 2022-01-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_alter_attendance_date_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_present',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
