# Generated by Django 3.2.11 on 2022-01-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default="{% static 'assets/img/profiles/avatar-02.jpg' %}", upload_to='profilePic'),
        ),
    ]
