# Generated by Django 3.2.11 on 2022-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default="{% static 'assets/img/profiles/avatar-02.jpg' %}", upload_to='attendance/profilePic'),
        ),
    ]
