# Generated by Django 3.2.11 on 2022-01-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_auto_20220122_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstName',
            new_name='FirstName',
        ),
    ]
