# Generated by Django 3.2.11 on 2022-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_rename_firstname_profile_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dateOfJoining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
