# Generated by Django 3.2.11 on 2022-01-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_profile_dateofjoining'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Junior', 'Junior'), ('Senior', 'Senior')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
