# Generated by Django 3.2.11 on 2022-01-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0041_alter_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednessday'), ('4', 'Thrusday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=20, null=True),
        ),
    ]
