# Generated by Django 3.2.11 on 2022-01-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0044_auto_20220123_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(blank=True, choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednessday'), ('3', 'Thrusday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=20, null=True),
        ),
    ]
