# Generated by Django 3.2.11 on 2022-01-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0046_delete_dayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayNum', models.CharField(blank=True, max_length=1, null=True)),
                ('dayName', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
